### ISSUE TITLE
Compilation fails on OSX due to missing 'TargetConditionals.h'

### ISSUE THREAD

**Issue by wmvanvliet** [Cpasjuste/eduke32_old#6]
I'm trying to compile eduke32 on OSX. When typing `make` I get the following error:

```
19:53 [master] ~/Downloads/eduke32> make
In file included from source/duke3d/src/game.cpp:25:
In file included from source/duke3d/src/duke3d.h:27:
source/build/include/compat.h:274:11: fatal error: 'TargetConditionals.h' file not found
# include <TargetConditionals.h>
          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Failed building obj/duke3d/game.o from source/duke3d/src/game.cpp!
make: *** [obj/duke3d/game.o] Error 1
```

I've searched around and `TargetConditionals.h` lives in `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`.

I don't have much experience with building things on OSX, could one of you give me a hint of how to to tweak the makefiles to include the right folders?

**Comment by Jan200101** [comment]
running just `make` will compile it for your platform
you have to run `make PLATFORM=SWITCH` with devkita64 installed

**Comment by wmvanvliet** [comment]
I'm not trying to build it for a switch, I'm trying to build it on a MacBook for its native platform, OSX.

**Comment by Jan200101** [comment]
If you want to build eduke32 for MacOS then I think this is the wrong place to ask that, this is dedicated to the Switch port of eduke32 afterall

your best bet is to look at the [wiki](https://wiki.eduke32.com/wiki/Building_EDuke32_on_macOS) and getting the latest revision of the [source code](https://wiki.eduke32.com/wiki/Acquiring_the_EDuke32_Source_Code)

**Comment by wmvanvliet** [comment]
ah, ok, sorry about that.
